### ISSUE TITLE
add "subscribe to feature release"

### ISSUE THREAD

**Issue by wilzbach** [storyscript/studio#131]
### Story
As a user,
When I click on an unimplemented feature,
I see a dialog box with a subscribe button

### Acceptance
**Given** unimplemented feature,
**When** click,
**Then** I see subscribe dialog

### Notes

![image](https://user-images.githubusercontent.com/4370550/69332925-f62c2e00-0c57-11ea-8016-effeec5968aa.png)

**Comment by JeanBarriere** [comment]
As design evolved, closing this issue as it's out of date
