### ISSUE TITLE
Comments show previous entries

### ISSUE THREAD

**Issue by stevepeak** [storyscript/studio#155]
https://share.getcloudapp.com/NQuvL4LD

Comments should not suggestions/previous entries.

**Comment by Arinono** [comment]
https://github.com/storyscript/studio/blob/453b2ea314d6d40195f4e5b34f5e0f098fda6a32/src/components/Comments.vue#L44-L51
```html
    <s-input
        v-model="commentInput"
        name="comment"
        small
        class="max-w-sm mx-4 flex-1"
        placeholder="write a comment..."
        autocomplete="off"                       <====== Add this line shoudl work fine
        @keyup.enter="addComment"
    />
```

Just to leave a trace of what is probably needed
