### ISSUE TITLE
Left pane uses same space even when collapsed

### ISSUE THREAD

**Issue by wilzbach** [storyscript/studio#308]
### Issue

Left pane uses too much padding when collpased.

**To Reproduce**
1. Go to a storyscript example
2. Resize window to e.g. 900px
3. Hide left pane

**Screenshots**

![image](https://user-images.githubusercontent.com/4370550/72979559-e86e6280-3dd8-11ea-9c1c-426e75e104e4.png)

Collapsed:

![image](https://user-images.githubusercontent.com/4370550/72979408-8dd50680-3dd8-11ea-99eb-34e4e1476234.png)

### Acceptance
**Given** [Initial state],
**When** window resize,
**Then** I shouldn't see so much padding around the left pane

**Comment by Arinono** [comment]
Since the ew design doesn't allow the left pane to be closed, I'm closing this issue.

<img width="560" alt="Screenshot 2020-02-07 at 18 43 59" src="https://user-images.githubusercontent.com/10957531/74052223-d3e5b900-49d9-11ea-8eff-d90d0c4967e9.png">
